# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import assignment2_pb2 as assignment2__pb2


class Assignment2Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTweet = channel.unary_stream(
        '/Assignment2/GetTweet',
        request_serializer=assignment2__pb2.Empty.SerializeToString,
        response_deserializer=assignment2__pb2.Tweet.FromString,
        )
    self.GetReddit = channel.unary_stream(
        '/Assignment2/GetReddit',
        request_serializer=assignment2__pb2.Empty.SerializeToString,
        response_deserializer=assignment2__pb2.RedditData.FromString,
        )


class Assignment2Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTweet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetReddit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Assignment2Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTweet': grpc.unary_stream_rpc_method_handler(
          servicer.GetTweet,
          request_deserializer=assignment2__pb2.Empty.FromString,
          response_serializer=assignment2__pb2.Tweet.SerializeToString,
      ),
      'GetReddit': grpc.unary_stream_rpc_method_handler(
          servicer.GetReddit,
          request_deserializer=assignment2__pb2.Empty.FromString,
          response_serializer=assignment2__pb2.RedditData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Assignment2', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
