version: '3'
services:
  redis:
    image: redis:alpine
    ports: 
      - "6380:6379"
  webpage:
    build:
      context: .
      dockerfile: Webpage.Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - "redis"
  server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    ports: 
      - "50051:50051"
  twitter-client:
    build:
      context: .
      dockerfile: twitter-client.Dockerfile
    depends_on:
      - "server"
    command: ["./wait-for-it.sh", "server:50051", 
"--", "python", "twitter-client.py"]
  reddit-client:
    build:
      context: .
      dockerfile: reddit-client.Dockerfile
    depends_on:
      - "server"
    command: ["./wait-for-it.sh", "server:50051",
              "--", "python", "reddit-client.py"]
