apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-client-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: twitter-client
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: twitter-client
    spec:
      containers:
      - name: twitter-client
        image: cynes/twitter-client:latest